var d = new Date();
var weekday = ["Sunday", "Monday", "Tuesday", "Wednesday", "Friday", "Saturday"];
var x = d.getDay();
var randomImage = ["https://wi.wallpapertip.com/wsimgs/15-155208_desktop-puppy-wallpaper-hd.jpg", "http://www.petsworld.in/blog/wp-content/uploads/2014/09/running-cute-puppies.jpg", "https://wi.wallpapertip.com/wsimgs/156-1564365_golden-retriever-puppy-desktop-wallpaper-desktop-wallpaper-puppy.jpg", "https://wi.wallpapertip.com/wsimgs/156-1564140_free-puppy-wallpapers-for-computer-wallpaper-cave-cute.jpg", "https://wi.wallpapertip.com/wsimgs/156-1565522_puppies-desktop-wallpaper-desktop-background-puppies.jpg", "https://wi.wallpapertip.com/wsimgs/156-1566650_cute-puppies-desktop-wallpaper-cute-puppies.jpg"]
var time = d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds();
var dateTime = time;
var p = document.createElement('p')
var fim = document.createElement('img');
fim.src = randomImage[x];
document.getElementById("div1").appendChild(fim).style = "width:200px ;height:200px";
document.getElementById("div1").appendChild(p).innerHTML = "Random image 1 " + "<br>Current time: " + dateTime + "<br>Day: " + weekday[x];
var p2 = document.createElement('p');
var sim = document.createElement('img');
sim.src = randomImage[(x + 1) % 2];
document.getElementById("div2").appendChild(sim).style = "width:200px ;height:200px";
document.getElementById("div2").appendChild(p2).innerHTML = "Random image 2" + "<br>Current time: " + dateTime + "<br>Day: " + weekday[x];
var p3 = document.createElement('p')
var tim = document.createElement('img');
tim.src = randomImage[(x + 3) % 6];
document.getElementById("div3").appendChild(tim).style = "width:200px; height:200px";
document.getElementById("div3").appendChild(p3).innerHTML = "Random image 3" + "<br>Current time: " + dateTime + "<br>Day: " + weekday[x];
